services:
  - type: web
    name: wati-incoming-webhook
    env: node
    branch: main
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: WATI_API_ENDPOINT
        value: https://api.wati.io
      - key: PUBLIC_BASE_URL
        value: https://api.gaffarindia.in
      - key: DEFAULT_COUNTRY_CODE
        value: "91"
      - key: ADMIN_SECRET
        sync: false
      - key: WATI_API_TOKEN
        sync: false
      - key: WATI_CHANNEL_NUMBER
        sync: false
